version: '3.8'

services:
  # 1. SERVIÇO: MYSQL (Banco de Dados)
  mysql:
    image: mysql:8.0
    container_name: poojava-mysql
    ports:
      - "3306:3306"
    environment:
      # Credenciais que devem ser as mesmas em application.properties
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: java_poo
    volumes:
      # Persistência dos dados
      - mysql-data:/var/lib/mysql

  # 2. SERVIÇO: RABBITMQ (Broker de Mensagens)
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: poojava-rabbitmq
    ports:
      - "5672:5672"   # Porta de Mensageria
      - "15672:15672" # Porta da Interface de Gestão Web (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  # 3. SERVIÇO: APLICAÇÃO JAVA (Microserviço Spring Boot)
  app:
    build: . # Constrói a imagem usando o Dockerfile na pasta atual
    container_name: poojava-app
    ports:
      - "8080:8080"
    # Garante a ordem de inicialização
    depends_on:
      - mysql
      - rabbitmq
    environment:
      # Sobrescreve as configurações para usar os nomes dos containers como HOSTS
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/java_poo?useSSL=false
      SPRING_RABBITMQ_HOST: rabbitmq

# Volumes para persistência
volumes:
  mysql-data:
